/**
 * Spaceflight News API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Author } from './author';
import { Event } from './event';
import { Launch } from './launch';


export interface Blog { 
    readonly id: number;
    title: string;
    authors: Array<Author>;
    url: string;
    image_url: string;
    readonly news_site: string;
    summary: string;
    published_at: string;
    readonly updated_at: string;
    featured?: boolean;
    launches: Array<Launch>;
    events: Array<Event>;
}

