/**
 * Spaceflight News API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Blog } from './blog';


export interface PaginatedBlogList { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Blog>;
}

