/**
 * Spaceflight News API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Report } from './report';


export interface PaginatedReportList { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Report>;
}

